# 服务器配置
server:
  port: 8081  # 设置Service A的运行端口

# Resilience4j断路器配置
resilience4j.circuitbreaker:
  instances:
    serviceB:  # 为Service B调用配置断路器实例
      slidingWindowSize: 5  # 滑动窗口大小，用于计算失败率
      failureRateThreshold: 50  # 失败率阈值，超过此值将打开断路器（百分比）
      waitDurationInOpenState: 5000  # 断路器打开状态的等待时间（毫秒）
      permittedNumberOfCallsInHalfOpenState: 3  # 半开状态下允许的调用次数
      automatic-transition-from-open-to-half-open-enabled: true #自动从打开转换为启用半开
      minimum-number-of-calls: 5 #最小调用次数
      sliding-window-type: count_based #滑动窗口类型 基于计数
#management:
#  endpoints:
#    web:
#      exposure:
#        include:
#          - '*'
#  endpoint:
#    health:
#      show-details: always
#  health:
#    circuitbreakers:
#      enabled: true
#    ratelimiters:
#      enabled: true