server:
  port: 8080

management:
  prometheus:
    metrics:
      export:
        enabled: true
#  metrics:
#    export:
#      prometheus:
#        enabled: true
  server:
    port: 8080 # 可选配置，如果不配置该 port，直接使用 ${server.port}
  endpoints:
    health:
      enabled: true
    web:
      exposure:
        include: 'prometheus' # 测试使用，开启了所有端点，生产环境不建议 *
spring:
  application:
    name: hippo4j-server
  dynamic:
    thread-pool:
      monitor:
        enable: true # 是否开启采集线程池运行时数据
        collect-interval: 5000 # 采集线程池运行数据频率
        collect-types: micrometer # 采集线程池运行数据的类型。eg：log、micrometer。多个可以同时使用，默认 micrometer
        initial-delay: 10000 # 项目启动后延迟多久进行采集
        thread-pool-types: dynamic # 采集线程池的类型。eg：dynamic、web、adapter。可任意配置，默认 dynamic
  cloud:
#    compatibility-verifier:
#      enabled: false
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: 6d8e7e0d-f7e5-4d06-b7c6-f7e7c5b5c5c5
        group: DEFAULT_GROUP
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 6d8e7e0d-f7e5-4d06-b7c6-f7e7c5b5c5c5
  config:
   import: nacos:hippo4j-config.yml

